# Generated by Django 4.2 on 2025-05-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeepfakeDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deepfake', models.BooleanField()),
                ('confidence', models.FloatField()),
                ('video_url', models.URLField(blank=True, max_length=2000)),
                ('model_used', models.CharField(default='xception', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
