# Generated by Django 4.2 on 2025-05-12 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_type', models.CharField(choices=[('audio', 'Audio Analysis'), ('behavior', 'Behavior Analysis'), ('content', 'Content Safety'), ('text', 'Text Analysis'), ('usage', 'Usage Pattern'), ('video', 'Video Analysis')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('result', models.JSONField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('risk_level', models.IntegerField(default=0)),
                ('details', models.JSONField(default=dict)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.childprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
