# Generated by Django 4.2 on 2025-05-18 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_detectionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionlog',
            name='detection_type',
            field=models.CharField(choices=[('audio', 'Audio Analysis'), ('behavior', 'Behavior Analysis'), ('content', 'Content Safety'), ('text', 'Text Analysis'), ('usage', 'Usage Pattern'), ('video', 'Video Analysis'), ('flash', 'Flash Detection')], max_length=20),
        ),
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatlogs', to='monitoring.childprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
