# Generated by Django 4.2 on 2025-05-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeepfakeDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_deepfake', models.BooleanField()),
                ('confidence', models.FloatField()),
                ('video_url', models.URLField(max_length=500)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
