# Generated by Django 4.2 on 2025-05-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepfake_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deepfakedetection',
            name='model_used',
            field=models.CharField(default='xception', max_length=50),
        ),
        migrations.AlterField(
            model_name='deepfakedetection',
            name='video_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
